stages:
  - build-image

image-build-job:
  stage: build-image
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "dev" ]; then
        docker build -t $CI_REGISTRY_IMAGE:dev .
        docker push $CI_REGISTRY_IMAGE:dev
      else
        docker build -t $CI_REGISTRY_IMAGE .
        docker push $CI_REGISTRY_IMAGE
      fi
  
